### ISSUE TITLE
1.5.0?

### ISSUE THREAD

**Issue by jrochkind** [marcelolx/bootstrap-icons#12]
https://github.com/twbs/icons/releases/tag/v1.5.0

**Comment by marcelolx** [comment]
@jrochkind I'll release a new version today

**Comment by marcelolx** [comment]
@jrochkind Actually I had already released a version https://github.com/marcelolx/bootstrap-icons/releases/tag/v1.0.10 with bootstrap icons 1.5.0, have you upgraded your dependency to this version of the gem (v1.0.10)?

**Comment by jrochkind** [comment]
Oh ok thanks! I was just going by the README, which says "Bootstrap Icons: v1.4.0", maybe just a README issue!

Is there an easy way one could tell looking at the source in github which version of bootstrap icons is really included, if the README gets out of date?

**Comment by marcelolx** [comment]
Oh sorry about that, I'll update the readme.

Yes, this repo contains two gems, the bootstrap-icons gem and the bootstrap-icons-helper gem, in the bootstrap-icons gems is a package.json file which points to the current version of the bootstrap-icons that's being used https://github.com/marcelolx/bootstrap-icons/blob/master/bootstrap-icons-gem/package.json#L7
